

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HomeAgency.Web
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class homeagencyEntities : DbContext
{
    public homeagencyEntities()
        : base("name=homeagencyEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Discount> Discounts { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<PurchaseProduct> PurchaseProducts { get; set; }

    public virtual DbSet<Sell> Sells { get; set; }

    public virtual DbSet<SellProduct> SellProducts { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

